ALTER TABLE invoice_settings
ADD COLUMN IF NOT EXISTS current_number INT DEFAULT 0;

ALTER TABLE invoice_settings
ADD COLUMN IF NOT EXISTS created_at_epoch BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP);

ALTER TABLE invoice_settings
ADD COLUMN IF NOT EXISTS updated_at_epoch BIGINT DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP);
